### ISSUE TITLE
Reconsider function modifier

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/auditing-reference#2]
I want to discuss about check lists in [function](https://github.com/Onther-Tech/auditing-reference/tree/54560e5f0803adc2fd757631331b145b73ee7a62#function)

This two check lists are quite ambiguous.
1. Consider difference between `pure` and `view`
2. Consider difference between `external` and `public`

##### Consider difference between `pure` and `view`
First of all, If function doesn't change contract's state, but neither `pure` or `view` modifier is used, it is more worthy to use one of `pure` or `view` than to consider what to use between `pure` and `view`.

I recommend to use this 2 check lists.
- Use `view` if the function doesn't change state.
- Use `pure` if the function doesn't **even** read state.

##### Consider difference between `external` and `public`
`external` and `public` are quite different modifier in that `public` can be called __internally__ and __externally__. If function is called __internally__, `msg.sender` doesn't change. __external__ call always changes `msg.sender`. `external` function only permits __external__ call, unlike `public` modifier.

It is the main difference among `internal`, `public`, `external`. Cheaper gas fee is extra benefit provided by solidity compiler.

**Comment by shingonu** [comment]
I wrote in the sense that these keyword(`pure` / `view` and `external` and `public`) must be clearly understood and used.

But as you suggested, it seems necessary to describe it more for the purpose of use.
